### ISSUE TITLE
Account name lookup strings containing "&" or "#" return 500 errors

### ISSUE THREAD

**Issue by Garywoo** [jontaylor034/SDataFetch#1]
When I search for the string "Example & Example Ltd" , the XHR request is made to `https://xxxxxxxxxxxxx.com/sdata/slx/dynamic/-/accounts?where=AccountName%20eq%20'Example%20&%20Example%20Ltd'&format=json`
This results in a 500 error.

**Comment by jontaylor034** [comment]
Changed component encoding, this no longer returns a 500 error. If you can please test with an account that has & in the name to make sure the results are returned correctly.

**Comment by jontaylor034** [comment]
Resolved with latest commits, included fixes to other uri characters also causing issues.
